spring:
  application:
    name: charging.service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#
  datasource:
    url: jdbc:postgresql://localhost:5432/charging-management
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changemeinprod!
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true

server:
  port: 8082