spring:
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: auth.service


  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 10
          multiplier: 2.0
#    #    host: localhost
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest

  datasource:
#    url: jdbc:postgresql://localhost:5432/charging-management
    url: jdbc:postgresql://db:5432/charging-management
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changemeinprod!
    hibernate:
      ddl-auto: validate
  flyway:
#    baseline-on-migrate: true
#    baseline-description: "init"
#    baseline-version: 0
    enabled: true
    schemas: public


resilience4j:
  timelimiter:
    instances:
      driverValidation:
        timeout-duration: 50ms
        cancel-running-future: true


server:
  port: 8084

app:
  reporting:
    dir: build/reports